"""create_all_tables

Revision ID: d5cea2914eec
Revises: 
Create Date: 2025-12-12 21:54:05.389627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5cea2914eec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户UUID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名，唯一'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希（bcrypt）'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='邮箱地址'),
    sa.Column('preferences', sa.JSON(), nullable=True, comment='用户偏好设置（JSON格式）'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='注册时间'),
    sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True, comment='最后登录时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_email', ['email'], unique=False)
        batch_op.create_index('idx_username', ['username'], unique=False)

    op.create_table('papers',
    sa.Column('id', sa.String(length=36), nullable=False, comment='论文UUID'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户ID'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='磁盘存储路径'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件大小（字节）'),
    sa.Column('domain', sa.String(length=50), nullable=True, comment='论文领域'),
    sa.Column('status', sa.Enum('UPLOADED', 'PARSING', 'PARSED', 'FAILED', name='paperstatus'), server_default='uploaded', nullable=False, comment='解析状态'),
    sa.Column('parsed_content', sa.JSON(), nullable=True, comment='解析后的内容（JSON格式）'),
    sa.Column('parse_error', sa.Text(), nullable=True, comment='解析失败原因'),
    sa.Column('parse_progress', sa.Integer(), nullable=False, comment='解析进度（0-100）'),
    sa.Column('parsed_at', sa.TIMESTAMP(), nullable=True, comment='解析完成时间'),
    sa.Column('added_to_graph', sa.Boolean(), server_default='0', nullable=False, comment='是否已添加到图谱'),
    sa.Column('graph_episode_ids', sa.JSON(), nullable=True, comment='添加到图谱的Episode UUID列表'),
    sa.Column('added_to_graph_at', sa.TIMESTAMP(), nullable=True, comment='添加到图谱的时间'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='上传时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.create_index('idx_papers_added_to_graph', ['added_to_graph'], unique=False)
        batch_op.create_index('idx_papers_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_papers_domain', ['domain'], unique=False)
        batch_op.create_index('idx_papers_status', ['status'], unique=False)
        batch_op.create_index('idx_papers_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_papers_user_status', ['user_id', 'status'], unique=False)

    op.create_table('research_sessions',
    sa.Column('id', sa.String(length=36), nullable=False, comment='会话UUID'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='会话标题'),
    sa.Column('domains', sa.JSON(), nullable=False, comment="研究领域数组，如['AI','SE']"),
    sa.Column('description', sa.Text(), nullable=True, comment='会话描述'),
    sa.Column('message_count', sa.Integer(), nullable=False, comment='消息数量'),
    sa.Column('last_message_at', sa.TIMESTAMP(), nullable=True, comment='最后消息时间'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('research_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_rs_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_rs_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('idx_rs_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_rs_user_updated', ['user_id', 'updated_at'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False, comment='消息UUID'),
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='会话ID'),
    sa.Column('role', sa.Enum('USER', 'AGENT', name='messagerole'), nullable=False, comment='角色：user用户 / agent助手'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('context_string', sa.Text(), nullable=True, comment='格式化的context文本，前端直接展示'),
    sa.Column('context_data', sa.JSON(), nullable=True, comment='结构化context数据'),
    sa.Column('attached_papers', sa.JSON(), nullable=True, comment='附带的论文ID列表'),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='元数据：tokens、响应时间等'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['session_id'], ['research_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('idx_cm_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_cm_role', ['role'], unique=False)
        batch_op.create_index('idx_cm_session_id', ['session_id'], unique=False)
        batch_op.create_index('idx_cm_session_time', ['session_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('idx_cm_session_time')
        batch_op.drop_index('idx_cm_session_id')
        batch_op.drop_index('idx_cm_role')
        batch_op.drop_index('idx_cm_created_at')

    op.drop_table('chat_messages')
    with op.batch_alter_table('research_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_rs_user_updated')
        batch_op.drop_index('idx_rs_user_id')
        batch_op.drop_index('idx_rs_updated_at')
        batch_op.drop_index('idx_rs_created_at')

    op.drop_table('research_sessions')
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_index('idx_papers_user_status')
        batch_op.drop_index('idx_papers_user_id')
        batch_op.drop_index('idx_papers_status')
        batch_op.drop_index('idx_papers_domain')
        batch_op.drop_index('idx_papers_created_at')
        batch_op.drop_index('idx_papers_added_to_graph')

    op.drop_table('papers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_username')
        batch_op.drop_index('idx_email')
        batch_op.drop_index('idx_created_at')

    op.drop_table('users')
    # ### end Alembic commands ###
