"""Change paper domain to domains JSON

Revision ID: 19cda294e117
Revises: d5cea2914eec
Create Date: 2025-12-13 22:51:40.549259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '19cda294e117'
down_revision = 'd5cea2914eec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domains', sa.JSON(), nullable=True, comment="论文领域列表，如['AI','NLP']，由LLM分析abstract自动识别"))
        batch_op.drop_index(batch_op.f('idx_papers_domain'))
        batch_op.drop_column('domain')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='论文领域'))
        batch_op.create_index(batch_op.f('idx_papers_domain'), ['domain'], unique=False)
        batch_op.drop_column('domains')

    # ### end Alembic commands ###
